#ifndef CAN_DECODE_AUTO_H
#define CAN_DECODE_AUTO_H

#include <stdint.h>
#include <stdbool.h>
#include "esp_err.h"
#include "can.h"
#include "esp_twai.h"
#include "esp_twai_onchip.h"
#include "esp_rom_crc.h"

extern bool BRestart;
extern bool BClearMinMax;
extern bool BClearErrors;
extern bool BReflashMode;
extern bool BNormalMode;
extern uint8_t NTargetDeviceID;
extern uint8_t tLastTaskTime1msTelemCar;
extern uint8_t tMaxTaskTime1msTelemCar;
extern uint8_t tLastTaskTime100msTelemCar;
extern uint8_t tMaxTaskTime100msTelemCar;
extern uint8_t tLastTaskTimeBGTelemCar;
extern uint8_t tMaxTaskTimeBGTelemCar;
extern uint16_t tSincePowerUpTelemCar;
extern uint8_t NLastResetReasonTelemCar;
extern uint8_t tLastTaskTime1msTelemPits;
extern uint8_t tMaxTaskTime1msTelemPits;
extern uint8_t tLastTaskTime100msTelemPits;
extern uint8_t tMaxTaskTime100msTelemPits;
extern uint8_t tLastTaskTimeBGTelemPits;
extern uint8_t tMaxTaskTimeBGTelemPits;
extern uint16_t tSincePowerUpTelemPits;
extern uint8_t NLastResetReasonTelemPits;
extern uint8_t tLastTaskTime1msIMDMon;
extern uint8_t tMaxTaskTime1msIMDMon;
extern uint8_t tLastTaskTime100msIMDMon;
extern uint8_t tMaxTaskTime100msIMDMon;
extern uint8_t tLastTaskTimeBGIMDMon;
extern uint8_t tMaxTaskTimeBGIMDMon;
extern uint16_t tSincePowerUpIMDMon;
extern uint8_t NLastResetReasonIMDMon;
extern uint8_t tLastTaskTime1msLogger;
extern uint8_t tMaxTaskTime1msLogger;
extern uint8_t tLastTaskTime100msLogger;
extern uint8_t tMaxTaskTime100msLogger;
extern uint8_t tLastTaskTimeBGLogger;
extern uint8_t tMaxTaskTimeBGLogger;
extern uint16_t tSincePowerUpLogger;
extern uint8_t NLastResetReasonLogger;
extern uint8_t tLastTaskTime1msPDU;
extern uint8_t tMaxTaskTime1msPDU;
extern uint8_t tLastTaskTime100msPDU;
extern uint8_t tMaxTaskTime100msPDU;
extern uint8_t tLastTaskTimeBGPDU;
extern uint8_t tMaxTaskTimeBGPDU;
extern uint16_t tSincePowerUpPDU;
extern uint8_t NLastResetReasonPDU;
extern uint8_t tLastTaskTime1msAPPS;
extern uint8_t tMaxTaskTime1msAPPS;
extern uint8_t tLastTaskTime100msAPPS;
extern uint8_t tMaxTaskTime100msAPPS;
extern uint8_t tLastTaskTimeBGAPPS;
extern uint8_t tMaxTaskTimeBGAPPS;
extern uint16_t tSincePowerUpAPPS;
extern uint8_t NLastResetReasonAPPS;
extern uint8_t tLastTaskTime1msScreen;
extern uint8_t tMaxTaskTime1msScreen;
extern uint8_t tLastTaskTime100msScreen;
extern uint8_t tMaxTaskTime100msScreen;
extern uint8_t tLastTaskTimeBGScreen;
extern uint8_t tMaxTaskTimeBGScreen;
extern uint16_t tSincePowerUpScreen;
extern uint8_t NLastResetReasonScreen;
extern uint8_t tLastTaskTime1msDash;
extern uint8_t tMaxTaskTime1msDash;
extern uint8_t tLastTaskTime100msDash;
extern uint8_t tMaxTaskTime100msDash;
extern uint8_t tLastTaskTimeBGDash;
extern uint8_t tMaxTaskTimeBGDash;
extern uint16_t tSincePowerUpDash;
extern uint8_t NLastResetReasonDash;
extern uint8_t tLastTaskTime1msDyno;
extern uint8_t tMaxTaskTime1msDyno;
extern uint8_t tLastTaskTime100msDyno;
extern uint8_t tMaxTaskTime100msDyno;
extern uint8_t tLastTaskTimeBGDyno;
extern uint8_t tMaxTaskTimeBGDyno;
extern uint16_t tSincePowerUpDyno;
extern uint8_t NLastResetReasonDyno;
extern uint8_t tLastTaskTime1msTempMon;
extern uint8_t tMaxTaskTime1msTempMon;
extern uint8_t tLastTaskTime100msTempMon;
extern uint8_t tMaxTaskTime100msTempMon;
extern uint8_t tLastTaskTimeBGTempMon;
extern uint8_t tMaxTaskTimeBGTempMon;
extern uint16_t tSincePowerUpTempMon;
extern uint8_t NLastResetReasonTempMon;
extern uint8_t tLastTaskTime1msContactorDriver;
extern uint8_t tMaxTaskTime1msContactorDriver;
extern uint8_t tLastTaskTime100msContactorDriver;
extern uint8_t tMaxTaskTime100msContactorDriver;
extern uint8_t tLastTaskTimeBGContactorDriver;
extern uint8_t tMaxTaskTimeBGContactorDriver;
extern uint16_t tSincePowerUpContactorDriver;
extern uint8_t NLastResetReasonContactorDriver;
extern float CMD_TargetAcCurrent;
extern bool BDashSwitchState;
extern bool BDashButtonState[2];
extern bool BTSActive;
extern bool BAIRPosClosed;
extern bool BAIRNegClosed;
extern bool BAIRPreClosed;
extern float rAIRPosDuty;
extern float rAIRNegDuty;
extern float rAIRPreDuty;
extern float IAIRPos;
extern float IAIRNeg;
extern float IAIRPre;
extern float VAIRDelta;
extern uint8_t CellID;
extern float VCell[112];
extern float RCell[112];
extern bool BBalancingCell[112];
extern float VOpenCell[112];
extern bool BIMDOff;
extern bool BIMDUnderVoltage;
extern bool BIMDStarting;
extern bool BIMDSSTGood;
extern bool BIMDDeviceError;
extern bool BIMDGroundConnectionFault;
extern bool BIMDInvalidState;
extern float RIsolation;
extern float fIMDPWM;
extern float rIMDPWM;
extern float CMD_TargetBrakeCurrent;
extern float CMD_TargetSpeed;
extern float rAPPs[2];
extern float rAPPsFinal;
extern bool BThrottleOK;
extern bool BAPPSFail[2];
extern bool BAPPSDrift;
extern float CMD_TargetPosition;
extern float VDynoPressureRaw[3];
extern float VDynoCoolantFlowRaw;
extern float VDynoTempRaw[3];
extern float pDynoPressure[3];
extern float VDynoCoolantFlow;
extern float TDynoTemp[3];
extern float rDynoFanDutyManual;
extern float rDynoPumpDutyManual;
extern uint8_t NDynoFanMode;
extern uint8_t NDynoPumpMode;
extern float CMD_TargetRelativeCurrent;
extern uint8_t rRadFanDuty;
extern uint8_t NRadFanMode;
extern float IRadFan;
extern uint8_t rPumpDuty[2];
extern uint8_t NPumpMode[2];
extern float IPump[2];
extern uint8_t rAccuFanDuty[2];
extern uint8_t NAccuFanMode[2];
extern float IAccuFan[2];
extern float IHorn;
extern float CMD_TargeRelativeBrakeCurrent;
extern bool CMD_SetDigOutput[4];
extern float CMD_MaxAcCurrent;
extern float CMD_MaxAcBrakeCurrent;
extern float CMD_MaxDcCurrent;
extern float CMD_MaxDcBrakeCurrent;
extern uint8_t CMD_DriveEnable;
extern float TFRTireChannel[16];
extern float TFLTireChannel[16];
extern float TRRTireChannel[16];
extern float TRLTireChannel[16];
extern uint8_t ControlMode;
extern float TargetIq;
extern float MotorPosition;
extern uint8_t isMotorStill;
extern float Actual_ERPM;
extern float Actual_Duty;
extern float Actual_InputVoltage;
extern float Actual_ACCurrent;
extern float Actual_DCCurrent;
extern float Actual_TempController;
extern float Actual_TempMotor;
extern uint8_t Actual_FaultCode;
extern float Actual_FOC_id;
extern float Actual_FOC_iq;
extern float Actual_Throttle;
extern float Actual_Brake;
extern bool Digital_output_[4];
extern bool Digital_input_[4];
extern uint8_t Drive_enable;
extern bool Motor_temp_limit;
extern bool Motor_accel_limit;
extern bool Input_voltage_limit;
extern bool IGBT_temp_limit;
extern bool IGBT_accel_limit;
extern bool Drive_enable_limit;
extern bool DC_current_limit;
extern bool Capacitor_temp_limit;
extern bool Power_limit;
extern bool RPM_max_limit;
extern bool RPM_min_limit;
extern uint8_t CAN_map_version;
extern float MaxAcCurrent;
extern float AvailableMaxAcCurrent;
extern float MinAcCurrent;
extern float AvailableMinAcCurrent;
extern float MaxDcCurrent;
extern float AvailableMaxDcCurrent;
extern float MinDcCurrent;
extern float AvailableMinDcCurrent;
extern uint8_t CellID_Temp;
extern bool BTCellInError[88];
extern bool BTCellSimulated[88];
extern uint8_t NTConversionMethodCell[88];
extern float VTADCCell[88];
extern float rTHealthStack[4];
extern float IPack;
extern float VPackInstant;
extern float rSOC;
extern bool Ready_Power_Signal;
extern bool Charge_Power_Signal;
extern bool Charge_Interlock;
extern bool Balancing_Active;
extern bool Discharge_Enable_Inverted;
extern bool Charge_Enable_Inverted;
extern bool Charge_Mode_Active_CAN;
extern bool MultiPurpose_Input;
extern bool DTC_P0A1F_Internal_Cell_Communication_Fault;
extern bool DTC_P0A12_Cell_Balancing_Stuck_Off_Fault;
extern bool DTC_P0A80_Weak_Cell_Fault;
extern bool DTC_P0AFA_Low_Cell_Voltage_Fault;
extern bool DTC_P0A04_Cell_Open_Wiring_Fault;
extern bool DTC_P0AC0_Current_Sensor_Fault;
extern bool DTC_P0A0D_Cell_Voltage_Over_5V_Fault;
extern bool DTC_P0A0F_Cell_Bank_Fault;
extern uint8_t IDischargeLimit;
extern float RPack;
extern float VPackTotal;
extern uint8_t TCellMax_BMS;
extern uint8_t TCellMin_BMS;
extern uint8_t NFailsafeStatus;
extern float VCellMin;
extern float VCellMax;
extern uint8_t NVCellMinID;
extern uint8_t NVCellMaxID;
extern bool DTC_P0A07_DischargeEnable_Relay_Fault;
extern bool DTC_P0A08_Charger_Safety_Relay_Fault;
extern bool DTC_P0A09_Internal_Hardware_Fault;
extern bool DTC_P0A0A_Internal_Heatsink_Thermistor_Fault;
extern bool DTC_P0A0B_Internal_Logic_Fault;
extern bool DTC_P0A0C_Highest_Cell_Voltage_Too_High_Fault;
extern bool DTC_P0A0E_Lowest_Cell_Voltage_Too_Low_Fault;
extern bool DTC_P0A10_Pack_Too_Hot_Fault;
extern float VCellAvg;
extern uint16_t VIPackSensor[2];
extern bool DTC_P0A95_High_Voltage_Interlock_Signal_Fault;
extern bool DTC_P0AA1_Precharge_Circuit_Malfunction;
extern bool DTC_P0A11_Abnormal_State_of_Charge_Behavior;
extern float Maximum_Cell_Voltage;
extern float Pack_CCL;
extern float Maximum_Pack_Voltage;
extern uint16_t NTCellID;
extern int8_t TCell[110];
extern int8_t TCellMin;
extern int8_t TCellMax;
extern uint8_t NTCellMaxID;
extern uint8_t NTCellMinID;
extern uint8_t NTempMonNumber;
extern int8_t TCellAvg;
extern uint8_t NCellTemps;
extern uint32_t NTempMonJ1939Address;
extern uint8_t NTempMonTargetAddress;

extern uint32_t tSinceESPControl;
extern bool BESPControlInError;
extern uint32_t tSinceMCUStatusTelemCar;
extern bool BMCUStatusTelemCarInError;
extern uint32_t tSinceMCUStatusTelemPits;
extern bool BMCUStatusTelemPitsInError;
extern uint32_t tSinceMCUStatusIMDMonitor;
extern bool BMCUStatusIMDMonitorInError;
extern uint32_t tSinceMCUStatusLogger;
extern bool BMCUStatusLoggerInError;
extern uint32_t tSinceMCUStatusPDU;
extern bool BMCUStatusPDUInError;
extern uint32_t tSinceStatusAPPS;
extern bool BStatusAPPSInError;
extern uint32_t tSinceMCUStatusScreen;
extern bool BMCUStatusScreenInError;
extern uint32_t tSinceMCUStatusDash;
extern bool BMCUStatusDashInError;
extern uint32_t tSinceMCUStatusDyno;
extern bool BMCUStatusDynoInError;
extern uint32_t tSinceMCUStatusTempMon;
extern bool BMCUStatusTempMonInError;
extern uint32_t tSinceMCUStatusContactorDriver;
extern bool BMCUStatusContactorDriverInError;
extern uint32_t tSinceSetAcCurrent;
extern bool BSetAcCurrentInError;
extern uint32_t tSinceDashData;
extern bool BDashDataInError;
extern uint32_t tSinceContactorDriverData;
extern bool BContactorDriverDataInError;
extern uint32_t tSinceCellVoltages;
extern bool BCellVoltagesInError;
extern uint32_t tSinceIMDData;
extern bool BIMDDataInError;
extern uint32_t tSinceSetBrakeCurrent;
extern bool BSetBrakeCurrentInError;
extern uint32_t tSinceSetERPM;
extern bool BSetERPMInError;
extern uint32_t tSinceStatusAPPSSensor;
extern bool BStatusAPPSSensorInError;
extern uint32_t tSinceSetPosition;
extern bool BSetPositionInError;
extern uint32_t tSinceDynoPressuresRaw;
extern bool BDynoPressuresRawInError;
extern uint32_t tSinceDynoTempsRaw;
extern bool BDynoTempsRawInError;
extern uint32_t tSinceDynoPressures;
extern bool BDynoPressuresInError;
extern uint32_t tSinceDynoTemps;
extern bool BDynoTempsInError;
extern uint32_t tSinceDynoCooling;
extern bool BDynoCoolingInError;
extern uint32_t tSinceSetRelCurrent;
extern bool BSetRelCurrentInError;
extern uint32_t tSincePDUStats1;
extern bool BPDUStats1InError;
extern uint32_t tSincePDUStats2;
extern bool BPDUStats2InError;
extern uint32_t tSincePDUStats3;
extern bool BPDUStats3InError;
extern uint32_t tSinceSetRelBrakeCurrent;
extern bool BSetRelBrakeCurrentInError;
extern uint32_t tSinceSetDigOutput;
extern bool BSetDigOutputInError;
extern uint32_t tSinceSetMaxAcCurrent;
extern bool BSetMaxAcCurrentInError;
extern uint32_t tSinceSetMaxAcBrakeCurrent;
extern bool BSetMaxAcBrakeCurrentInError;
extern uint32_t tSinceSetMaxDcCurrent;
extern bool BSetMaxDcCurrentInError;
extern uint32_t tSinceSetMaxDcBrakeCurrent;
extern bool BSetMaxDcBrakeCurrentInError;
extern uint32_t tSinceSetDriveEnable;
extern bool BSetDriveEnableInError;
extern uint32_t tSinceFRTireTemp1;
extern bool BFRTireTemp1InError;
extern uint32_t tSinceFRTireTemp2;
extern bool BFRTireTemp2InError;
extern uint32_t tSinceFRTireTemp3;
extern bool BFRTireTemp3InError;
extern uint32_t tSinceFRTireTemp4;
extern bool BFRTireTemp4InError;
extern uint32_t tSinceFLTireTemp1;
extern bool BFLTireTemp1InError;
extern uint32_t tSinceFLTireTemp2;
extern bool BFLTireTemp2InError;
extern uint32_t tSinceFLTireTemp3;
extern bool BFLTireTemp3InError;
extern uint32_t tSinceFLTireTemp4;
extern bool BFLTireTemp4InError;
extern uint32_t tSinceRRTireTemp1;
extern bool BRRTireTemp1InError;
extern uint32_t tSinceRRTireTemp2;
extern bool BRRTireTemp2InError;
extern uint32_t tSinceRRTireTemp3;
extern bool BRRTireTemp3InError;
extern uint32_t tSinceRRTireTemp4;
extern bool BRRTireTemp4InError;
extern uint32_t tSinceRLTireTemp1;
extern bool BRLTireTemp1InError;
extern uint32_t tSinceRLTireTemp2;
extern bool BRLTireTemp2InError;
extern uint32_t tSinceRLTireTemp3;
extern bool BRLTireTemp3InError;
extern uint32_t tSinceRLTireTemp4;
extern bool BRLTireTemp4InError;
extern uint32_t tSinceTargetIqInfo;
extern bool BTargetIqInfoInError;
extern uint32_t tSinceERPM_DUTY_VOLTAGE;
extern bool BERPM_DUTY_VOLTAGEInError;
extern uint32_t tSinceAC_DC_current;
extern bool BAC_DC_currentInError;
extern uint32_t tSinceTemperatures;
extern bool BTemperaturesInError;
extern uint32_t tSinceFOC;
extern bool BFOCInError;
extern uint32_t tSinceInverter_MISC;
extern bool BInverter_MISCInError;
extern uint32_t tSinceMinMaxAcCurrent;
extern bool BMinMaxAcCurrentInError;
extern uint32_t tSinceMinMaxDcCurrent;
extern bool BMinMaxDcCurrentInError;
extern uint32_t tSinceCellTempStats;
extern bool BCellTempStatsInError;
extern uint32_t tSinceCellStats1;
extern bool BCellStats1InError;
extern uint32_t tSinceCellStats2;
extern bool BCellStats2InError;
extern uint32_t tSinceCellStats3;
extern bool BCellStats3InError;
extern uint32_t tSinceCellStats4;
extern bool BCellStats4InError;
extern uint32_t tSinceElconInterface2;
extern bool BElconInterface2InError;
extern uint32_t tSinceElconInterface1;
extern bool BElconInterface1InError;
extern uint32_t tSinceElconInterface3;
extern bool BElconInterface3InError;
extern uint32_t tSinceCellTempGeneral;
extern bool BCellTempGeneralInError;
extern uint32_t tSinceBMSCellTemp;
extern bool BBMSCellTempInError;
extern uint32_t tSinceTempMonAddressCast;
extern bool BTempMonAddressCastInError;
#define ESPCONTROL_ID 0x10
#define ESPCONTROL_PERIOD_MS 100
#define ESPCONTROL_THRESH_MS 500
#define MCUSTATUSTELEMCAR_ID 0x11
#define MCUSTATUSTELEMCAR_PERIOD_MS 1000
#define MCUSTATUSTELEMCAR_THRESH_MS 5000
#define MCUSTATUSTELEMPITS_ID 0x12
#define MCUSTATUSTELEMPITS_PERIOD_MS 1000
#define MCUSTATUSTELEMPITS_THRESH_MS 5000
#define MCUSTATUSIMDMONITOR_ID 0x13
#define MCUSTATUSIMDMONITOR_PERIOD_MS 1000
#define MCUSTATUSIMDMONITOR_THRESH_MS 5000
#define MCUSTATUSLOGGER_ID 0x14
#define MCUSTATUSLOGGER_PERIOD_MS 1000
#define MCUSTATUSLOGGER_THRESH_MS 5000
#define MCUSTATUSPDU_ID 0x15
#define MCUSTATUSPDU_PERIOD_MS 1000
#define MCUSTATUSPDU_THRESH_MS 5000
#define STATUSAPPS_ID 0x16
#define STATUSAPPS_PERIOD_MS 1000
#define STATUSAPPS_THRESH_MS 5000
#define MCUSTATUSSCREEN_ID 0x17
#define MCUSTATUSSCREEN_PERIOD_MS 1000
#define MCUSTATUSSCREEN_THRESH_MS 5000
#define MCUSTATUSDASH_ID 0x18
#define MCUSTATUSDASH_PERIOD_MS 1000
#define MCUSTATUSDASH_THRESH_MS 5000
#define MCUSTATUSDYNO_ID 0x19
#define MCUSTATUSDYNO_PERIOD_MS 1000
#define MCUSTATUSDYNO_THRESH_MS 5000
#define MCUSTATUSTEMPMON_ID 0x1A
#define MCUSTATUSTEMPMON_PERIOD_MS 1000
#define MCUSTATUSTEMPMON_THRESH_MS 5000
#define MCUSTATUSCONTACTORDRIVER_ID 0x1B
#define MCUSTATUSCONTACTORDRIVER_PERIOD_MS 1000
#define MCUSTATUSCONTACTORDRIVER_THRESH_MS 5000
#define SETACCURRENT_ID 0x24
#define SETACCURRENT_PERIOD_MS 100
#define SETACCURRENT_THRESH_MS 500
#define DASHDATA_ID 0x33
#define DASHDATA_PERIOD_MS 100
#define DASHDATA_THRESH_MS 500
#define CONTACTORDRIVERDATA_ID 0x34
#define CONTACTORDRIVERDATA_PERIOD_MS 100
#define CONTACTORDRIVERDATA_THRESH_MS 500
#define CELLVOLTAGES_ID 0x36
#define CELLVOLTAGES_PERIOD_MS 8
#define CELLVOLTAGES_THRESH_MS 40
#define IMDDATA_ID 0x40
#define IMDDATA_PERIOD_MS 100
#define IMDDATA_THRESH_MS 500
#define SETBRAKECURRENT_ID 0x44
#define SETBRAKECURRENT_PERIOD_MS 100
#define SETBRAKECURRENT_THRESH_MS 500
#define SETERPM_ID 0x64
#define SETERPM_PERIOD_MS 100
#define SETERPM_THRESH_MS 500
#define STATUSAPPSSENSOR_ID 0x81
#define STATUSAPPSSENSOR_PERIOD_MS 100
#define STATUSAPPSSENSOR_THRESH_MS 500
#define SETPOSITION_ID 0x84
#define SETPOSITION_PERIOD_MS 100
#define SETPOSITION_THRESH_MS 500
#define DYNOPRESSURESRAW_ID 0x90
#define DYNOPRESSURESRAW_PERIOD_MS 100
#define DYNOPRESSURESRAW_THRESH_MS 500
#define DYNOTEMPSRAW_ID 0x91
#define DYNOTEMPSRAW_PERIOD_MS 100
#define DYNOTEMPSRAW_THRESH_MS 500
#define DYNOPRESSURES_ID 0x92
#define DYNOPRESSURES_PERIOD_MS 100
#define DYNOPRESSURES_THRESH_MS 500
#define DYNOTEMPS_ID 0x93
#define DYNOTEMPS_PERIOD_MS 100
#define DYNOTEMPS_THRESH_MS 500
#define DYNOCOOLING_ID 0x94
#define DYNOCOOLING_PERIOD_MS 100
#define DYNOCOOLING_THRESH_MS 500
#define SETRELCURRENT_ID 0xA4
#define SETRELCURRENT_PERIOD_MS 1
#define SETRELCURRENT_THRESH_MS 5
#define PDUSTATS1_ID 0xB0
#define PDUSTATS1_PERIOD_MS 100
#define PDUSTATS1_THRESH_MS 500
#define PDUSTATS2_ID 0xB1
#define PDUSTATS2_PERIOD_MS 100
#define PDUSTATS2_THRESH_MS 500
#define PDUSTATS3_ID 0xB2
#define PDUSTATS3_PERIOD_MS 100
#define PDUSTATS3_THRESH_MS 500
#define SETRELBRAKECURRENT_ID 0xC4
#define SETRELBRAKECURRENT_PERIOD_MS 100
#define SETRELBRAKECURRENT_THRESH_MS 500
#define SETDIGOUTPUT_ID 0xE4
#define SETDIGOUTPUT_PERIOD_MS 100
#define SETDIGOUTPUT_THRESH_MS 500
#define SETMAXACCURRENT_ID 0x104
#define SETMAXACCURRENT_PERIOD_MS 100
#define SETMAXACCURRENT_THRESH_MS 500
#define SETMAXACBRAKECURRENT_ID 0x124
#define SETMAXACBRAKECURRENT_PERIOD_MS 100
#define SETMAXACBRAKECURRENT_THRESH_MS 500
#define SETMAXDCCURRENT_ID 0x144
#define SETMAXDCCURRENT_PERIOD_MS 100
#define SETMAXDCCURRENT_THRESH_MS 500
#define SETMAXDCBRAKECURRENT_ID 0x164
#define SETMAXDCBRAKECURRENT_PERIOD_MS 100
#define SETMAXDCBRAKECURRENT_THRESH_MS 500
#define SETDRIVEENABLE_ID 0x184
#define SETDRIVEENABLE_PERIOD_MS 100
#define SETDRIVEENABLE_THRESH_MS 500
#define FRTIRETEMP1_ID 0x200
#define FRTIRETEMP1_PERIOD_MS 30
#define FRTIRETEMP1_THRESH_MS 150
#define FRTIRETEMP2_ID 0x201
#define FRTIRETEMP2_PERIOD_MS 30
#define FRTIRETEMP2_THRESH_MS 150
#define FRTIRETEMP3_ID 0x202
#define FRTIRETEMP3_PERIOD_MS 30
#define FRTIRETEMP3_THRESH_MS 150
#define FRTIRETEMP4_ID 0x203
#define FRTIRETEMP4_PERIOD_MS 30
#define FRTIRETEMP4_THRESH_MS 150
#define FLTIRETEMP1_ID 0x204
#define FLTIRETEMP1_PERIOD_MS 30
#define FLTIRETEMP1_THRESH_MS 150
#define FLTIRETEMP2_ID 0x205
#define FLTIRETEMP2_PERIOD_MS 30
#define FLTIRETEMP2_THRESH_MS 150
#define FLTIRETEMP3_ID 0x206
#define FLTIRETEMP3_PERIOD_MS 30
#define FLTIRETEMP3_THRESH_MS 150
#define FLTIRETEMP4_ID 0x207
#define FLTIRETEMP4_PERIOD_MS 30
#define FLTIRETEMP4_THRESH_MS 150
#define RRTIRETEMP1_ID 0x208
#define RRTIRETEMP1_PERIOD_MS 30
#define RRTIRETEMP1_THRESH_MS 150
#define RRTIRETEMP2_ID 0x209
#define RRTIRETEMP2_PERIOD_MS 30
#define RRTIRETEMP2_THRESH_MS 150
#define RRTIRETEMP3_ID 0x20A
#define RRTIRETEMP3_PERIOD_MS 30
#define RRTIRETEMP3_THRESH_MS 150
#define RRTIRETEMP4_ID 0x20B
#define RRTIRETEMP4_PERIOD_MS 30
#define RRTIRETEMP4_THRESH_MS 150
#define RLTIRETEMP1_ID 0x20C
#define RLTIRETEMP1_PERIOD_MS 30
#define RLTIRETEMP1_THRESH_MS 150
#define RLTIRETEMP2_ID 0x20D
#define RLTIRETEMP2_PERIOD_MS 30
#define RLTIRETEMP2_THRESH_MS 150
#define RLTIRETEMP3_ID 0x20E
#define RLTIRETEMP3_PERIOD_MS 30
#define RLTIRETEMP3_THRESH_MS 150
#define RLTIRETEMP4_ID 0x20F
#define RLTIRETEMP4_PERIOD_MS 30
#define RLTIRETEMP4_THRESH_MS 150
#define TARGETIQINFO_ID 0x3E4
#define TARGETIQINFO_PERIOD_MS 25
#define TARGETIQINFO_THRESH_MS 125
#define ERPM_DUTY_VOLTAGE_ID 0x404
#define ERPM_DUTY_VOLTAGE_PERIOD_MS 25
#define ERPM_DUTY_VOLTAGE_THRESH_MS 125
#define AC_DC_CURRENT_ID 0x424
#define AC_DC_CURRENT_PERIOD_MS 25
#define AC_DC_CURRENT_THRESH_MS 125
#define TEMPERATURES_ID 0x444
#define TEMPERATURES_PERIOD_MS 25
#define TEMPERATURES_THRESH_MS 125
#define FOC_ID 0x464
#define FOC_PERIOD_MS 25
#define FOC_THRESH_MS 125
#define INVERTER_MISC_ID 0x484
#define INVERTER_MISC_PERIOD_MS 25
#define INVERTER_MISC_THRESH_MS 125
#define MINMAXACCURRENT_ID 0x4A4
#define MINMAXACCURRENT_PERIOD_MS 25
#define MINMAXACCURRENT_THRESH_MS 125
#define MINMAXDCCURRENT_ID 0x4C4
#define MINMAXDCCURRENT_PERIOD_MS 25
#define MINMAXDCCURRENT_THRESH_MS 125
#define CELLTEMPSTATS_ID 0x6A0
#define CELLTEMPSTATS_PERIOD_MS 100
#define CELLTEMPSTATS_THRESH_MS 500
#define CELLSTATS1_ID 0x6B0
#define CELLSTATS1_PERIOD_MS 8
#define CELLSTATS1_THRESH_MS 40
#define CELLSTATS2_ID 0x6B1
#define CELLSTATS2_PERIOD_MS 8
#define CELLSTATS2_THRESH_MS 40
#define CELLSTATS3_ID 0x6B2
#define CELLSTATS3_PERIOD_MS 8
#define CELLSTATS3_THRESH_MS 40
#define CELLSTATS4_ID 0x6B3
#define CELLSTATS4_PERIOD_MS 8
#define CELLSTATS4_THRESH_MS 40
#define ELCONINTERFACE2_ID 0x1806E5F4
#define ELCONINTERFACE2_PERIOD_MS 808
#define ELCONINTERFACE2_THRESH_MS 4040
#define ELCONINTERFACE1_ID 0x1806E7F4
#define ELCONINTERFACE1_PERIOD_MS 808
#define ELCONINTERFACE1_THRESH_MS 4040
#define ELCONINTERFACE3_ID 0x1806E9F4
#define ELCONINTERFACE3_PERIOD_MS 808
#define ELCONINTERFACE3_THRESH_MS 4040
#define CELLTEMPGENERAL_ID 0x1838F380
#define CELLTEMPGENERAL_PERIOD_MS 100
#define CELLTEMPGENERAL_THRESH_MS 500
#define BMSCELLTEMP_ID 0x1839F380
#define BMSCELLTEMP_PERIOD_MS 100
#define BMSCELLTEMP_THRESH_MS 500
#define TEMPMONADDRESSCAST_ID 0x18EEFF80
#define TEMPMONADDRESSCAST_PERIOD_MS 200
#define TEMPMONADDRESSCAST_THRESH_MS 1000

<<<<<<< HEAD
esp_err_t ESPControlRx(CAN_frame_t stFrame);
esp_err_t ESPControlTx(twai_node_handle_t stCANBus);
esp_err_t MCUStatusTelemCarRx(CAN_frame_t stFrame);
esp_err_t MCUStatusTelemCarTx(twai_node_handle_t stCANBus);
esp_err_t MCUStatusTelemPitsRx(CAN_frame_t stFrame);
esp_err_t MCUStatusTelemPitsTx(twai_node_handle_t stCANBus);
esp_err_t MCUStatusIMDMonitorRx(CAN_frame_t stFrame);
esp_err_t MCUStatusIMDMonitorTx(twai_node_handle_t stCANBus);
esp_err_t MCUStatusLoggerRx(CAN_frame_t stFrame);
esp_err_t MCUStatusLoggerTx(twai_node_handle_t stCANBus);
esp_err_t MCUStatusPDURx(CAN_frame_t stFrame);
esp_err_t MCUStatusPDUTx(twai_node_handle_t stCANBus);
esp_err_t StatusAPPSRx(CAN_frame_t stFrame);
esp_err_t StatusAPPSTx(twai_node_handle_t stCANBus);
esp_err_t MCUStatusScreenRx(CAN_frame_t stFrame);
esp_err_t MCUStatusScreenTx(twai_node_handle_t stCANBus);
esp_err_t MCUStatusDashRx(CAN_frame_t stFrame);
esp_err_t MCUStatusDashTx(twai_node_handle_t stCANBus);
esp_err_t MCUStatusDynoRx(CAN_frame_t stFrame);
esp_err_t MCUStatusDynoTx(twai_node_handle_t stCANBus);
esp_err_t MCUStatusTempMonRx(CAN_frame_t stFrame);
esp_err_t MCUStatusTempMonTx(twai_node_handle_t stCANBus);
esp_err_t MCUStatusContactorDriverRx(CAN_frame_t stFrame);
esp_err_t MCUStatusContactorDriverTx(twai_node_handle_t stCANBus);
esp_err_t SetAcCurrentRx(CAN_frame_t stFrame);
esp_err_t SetAcCurrentTx(twai_node_handle_t stCANBus);
esp_err_t DashDataRx(CAN_frame_t stFrame);
esp_err_t DashDataTx(twai_node_handle_t stCANBus);
esp_err_t ContactorDriverDataRx(CAN_frame_t stFrame);
esp_err_t ContactorDriverDataTx(twai_node_handle_t stCANBus);
esp_err_t CellVoltagesRx(CAN_frame_t stFrame);
esp_err_t CellVoltagesTx(twai_node_handle_t stCANBus);
esp_err_t IMDDataRx(CAN_frame_t stFrame);
esp_err_t IMDDataTx(twai_node_handle_t stCANBus);
esp_err_t SetBrakeCurrentRx(CAN_frame_t stFrame);
esp_err_t SetBrakeCurrentTx(twai_node_handle_t stCANBus);
esp_err_t SetERPMRx(CAN_frame_t stFrame);
esp_err_t SetERPMTx(twai_node_handle_t stCANBus);
esp_err_t StatusAPPSSensorRx(CAN_frame_t stFrame);
esp_err_t StatusAPPSSensorTx(twai_node_handle_t stCANBus);
esp_err_t SetPositionRx(CAN_frame_t stFrame);
esp_err_t SetPositionTx(twai_node_handle_t stCANBus);
esp_err_t DynoPressuresRawRx(CAN_frame_t stFrame);
esp_err_t DynoPressuresRawTx(twai_node_handle_t stCANBus);
esp_err_t DynoTempsRawRx(CAN_frame_t stFrame);
esp_err_t DynoTempsRawTx(twai_node_handle_t stCANBus);
esp_err_t DynoPressuresRx(CAN_frame_t stFrame);
esp_err_t DynoPressuresTx(twai_node_handle_t stCANBus);
esp_err_t DynoTempsRx(CAN_frame_t stFrame);
esp_err_t DynoTempsTx(twai_node_handle_t stCANBus);
esp_err_t DynoCoolingRx(CAN_frame_t stFrame);
esp_err_t DynoCoolingTx(twai_node_handle_t stCANBus);
esp_err_t SetRelCurrentRx(CAN_frame_t stFrame);
esp_err_t SetRelCurrentTx(twai_node_handle_t stCANBus);
esp_err_t PDUStats1Rx(CAN_frame_t stFrame);
esp_err_t PDUStats1Tx(twai_node_handle_t stCANBus);
esp_err_t PDUStats2Rx(CAN_frame_t stFrame);
esp_err_t PDUStats2Tx(twai_node_handle_t stCANBus);
esp_err_t PDUStats3Rx(CAN_frame_t stFrame);
esp_err_t PDUStats3Tx(twai_node_handle_t stCANBus);
esp_err_t SetRelBrakeCurrentRx(CAN_frame_t stFrame);
esp_err_t SetRelBrakeCurrentTx(twai_node_handle_t stCANBus);
esp_err_t SetDigOutputRx(CAN_frame_t stFrame);
esp_err_t SetDigOutputTx(twai_node_handle_t stCANBus);
esp_err_t SetMaxAcCurrentRx(CAN_frame_t stFrame);
esp_err_t SetMaxAcCurrentTx(twai_node_handle_t stCANBus);
esp_err_t SetMaxAcBrakeCurrentRx(CAN_frame_t stFrame);
esp_err_t SetMaxAcBrakeCurrentTx(twai_node_handle_t stCANBus);
esp_err_t SetMaxDcCurrentRx(CAN_frame_t stFrame);
esp_err_t SetMaxDcCurrentTx(twai_node_handle_t stCANBus);
esp_err_t SetMaxDcBrakeCurrentRx(CAN_frame_t stFrame);
esp_err_t SetMaxDcBrakeCurrentTx(twai_node_handle_t stCANBus);
esp_err_t SetDriveEnableRx(CAN_frame_t stFrame);
esp_err_t SetDriveEnableTx(twai_node_handle_t stCANBus);
esp_err_t FRTireTemp1Rx(CAN_frame_t stFrame);
esp_err_t FRTireTemp1Tx(twai_node_handle_t stCANBus);
esp_err_t FRTireTemp2Rx(CAN_frame_t stFrame);
esp_err_t FRTireTemp2Tx(twai_node_handle_t stCANBus);
esp_err_t FRTireTemp3Rx(CAN_frame_t stFrame);
esp_err_t FRTireTemp3Tx(twai_node_handle_t stCANBus);
esp_err_t FRTireTemp4Rx(CAN_frame_t stFrame);
esp_err_t FRTireTemp4Tx(twai_node_handle_t stCANBus);
esp_err_t FLTireTemp1Rx(CAN_frame_t stFrame);
esp_err_t FLTireTemp1Tx(twai_node_handle_t stCANBus);
esp_err_t FLTireTemp2Rx(CAN_frame_t stFrame);
esp_err_t FLTireTemp2Tx(twai_node_handle_t stCANBus);
esp_err_t FLTireTemp3Rx(CAN_frame_t stFrame);
esp_err_t FLTireTemp3Tx(twai_node_handle_t stCANBus);
esp_err_t FLTireTemp4Rx(CAN_frame_t stFrame);
esp_err_t FLTireTemp4Tx(twai_node_handle_t stCANBus);
esp_err_t RRTireTemp1Rx(CAN_frame_t stFrame);
esp_err_t RRTireTemp1Tx(twai_node_handle_t stCANBus);
esp_err_t RRTireTemp2Rx(CAN_frame_t stFrame);
esp_err_t RRTireTemp2Tx(twai_node_handle_t stCANBus);
esp_err_t RRTireTemp3Rx(CAN_frame_t stFrame);
esp_err_t RRTireTemp3Tx(twai_node_handle_t stCANBus);
esp_err_t RRTireTemp4Rx(CAN_frame_t stFrame);
esp_err_t RRTireTemp4Tx(twai_node_handle_t stCANBus);
esp_err_t RLTireTemp1Rx(CAN_frame_t stFrame);
esp_err_t RLTireTemp1Tx(twai_node_handle_t stCANBus);
esp_err_t RLTireTemp2Rx(CAN_frame_t stFrame);
esp_err_t RLTireTemp2Tx(twai_node_handle_t stCANBus);
esp_err_t RLTireTemp3Rx(CAN_frame_t stFrame);
esp_err_t RLTireTemp3Tx(twai_node_handle_t stCANBus);
esp_err_t RLTireTemp4Rx(CAN_frame_t stFrame);
esp_err_t RLTireTemp4Tx(twai_node_handle_t stCANBus);
esp_err_t TargetIqInfoRx(CAN_frame_t stFrame);
esp_err_t TargetIqInfoTx(twai_node_handle_t stCANBus);
esp_err_t ERPM_DUTY_VOLTAGERx(CAN_frame_t stFrame);
esp_err_t ERPM_DUTY_VOLTAGETx(twai_node_handle_t stCANBus);
esp_err_t AC_DC_currentRx(CAN_frame_t stFrame);
esp_err_t AC_DC_currentTx(twai_node_handle_t stCANBus);
esp_err_t TemperaturesRx(CAN_frame_t stFrame);
esp_err_t TemperaturesTx(twai_node_handle_t stCANBus);
esp_err_t FOCRx(CAN_frame_t stFrame);
esp_err_t FOCTx(twai_node_handle_t stCANBus);
esp_err_t Inverter_MISCRx(CAN_frame_t stFrame);
esp_err_t Inverter_MISCTx(twai_node_handle_t stCANBus);
esp_err_t MinMaxAcCurrentRx(CAN_frame_t stFrame);
esp_err_t MinMaxAcCurrentTx(twai_node_handle_t stCANBus);
esp_err_t MinMaxDcCurrentRx(CAN_frame_t stFrame);
esp_err_t MinMaxDcCurrentTx(twai_node_handle_t stCANBus);
esp_err_t CellTempStatsRx(CAN_frame_t stFrame);
esp_err_t CellTempStatsTx(twai_node_handle_t stCANBus);
esp_err_t CellStats1Rx(CAN_frame_t stFrame);
esp_err_t CellStats1Tx(twai_node_handle_t stCANBus);
esp_err_t CellStats2Rx(CAN_frame_t stFrame);
esp_err_t CellStats2Tx(twai_node_handle_t stCANBus);
esp_err_t CellStats3Rx(CAN_frame_t stFrame);
esp_err_t CellStats3Tx(twai_node_handle_t stCANBus);
esp_err_t CellStats4Rx(CAN_frame_t stFrame);
esp_err_t CellStats4Tx(twai_node_handle_t stCANBus);
esp_err_t ElconInterface2Rx(CAN_frame_t stFrame);
esp_err_t ElconInterface2Tx(twai_node_handle_t stCANBus);
esp_err_t ElconInterface1Rx(CAN_frame_t stFrame);
esp_err_t ElconInterface1Tx(twai_node_handle_t stCANBus);
esp_err_t ElconInterface3Rx(CAN_frame_t stFrame);
esp_err_t ElconInterface3Tx(twai_node_handle_t stCANBus);
esp_err_t CellTempGeneralRx(CAN_frame_t stFrame);
esp_err_t CellTempGeneralTx(twai_node_handle_t stCANBus);
esp_err_t BMSCellTempRx(CAN_frame_t stFrame);
esp_err_t BMSCellTempTx(twai_node_handle_t stCANBus);
esp_err_t TempMonAddressCastRx(CAN_frame_t stFrame);
esp_err_t TempMonAddressCastTx(twai_node_handle_t stCANBus);

void CANRxCheck1ms(void);
void CANRxCheck100ms(void);


#endif
